### ISSUE TITLE
No Customer Id required for new Subscription for new customer

### ISSUE THREAD

**Issue by aaronseabaugh** [teference/zoho-dotnet#5]
Curious if the component can be modified to support new subscriptions for new customer passing in customer information so when the subscription gets created so does the customer.. 

Currently Zoho does not require a customer id for new subscriptions from the JSON api.  The c# api  requires a customer id.

If there are alternatives let me know.

**Comment by jsinh** [comment]
Thanks for reaching out @aaronseabaugh 
This is new information to me. When I started with their implementation that was not the case (or at least till I know and in the way I tested). Let me confirm this with few test internally and get back to you.

**Comment by aaronseabaugh** [comment]
That would be awesome!   Thanks!  Impressive response time!   Again thanks!

**Comment by jsinh** [comment]
@aaronseabaugh 
Pushed a [NuGet update v0.6.17](https://www.nuget.org/packages/Zoho.Api/0.6.17) which contains "Customer" property to fill up customer info during creating customer call (instead of mentioning customer_id). [Release details](https://github.com/teference/zoho-dotnet/releases/tag/v0.6.17)

Closing this thread, let me know if you are still having an issue creating a subscription. Cheers!
